# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Dart OS
description: >- # this means to ignore newlines until "baseurl:"
  Dart OS
baseurl: "/" # the subpath of the site
url: "https://dart-os.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "G-NC3B6J6580"


social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Dart OS
  email: sys41x4@zohomail.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://www.gitlab.com/dart-os   # Project Repository
    - https://github.com/dart-os       # change to your github homepage
    - https://twitter.com/dart_os      # change to your twitter homepage
    # Uncomment below to add more social links
    - https://www.linkedin.com/in/sys41x4


header:
  pages:
    - name: Home
      slug: /
    - name: Downloads
    - name: Project
    - name: About
    - name: Links
    - name: Donate

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: sys41x4@zohomail.in
      icon: "fa fa-envelope"
      link: mailto:sys41x4@zohomail.in
    - name: Discord
      icon: "fa fa-group"
      value: "Discord"
      info: "Join the Discord Community at <strong>101 Bytes</strong>, or scan the joining QR code:"
      infoImg: "/assets/img/101-Bytes-discord-qr-code.png"
      link: "https://discord.gg/8My5m9jNMG"
    - name: Reddit
      icon: "fa fa-reddit"
      value: "Reddit"
      info: "Join the Reddit Community at <strong>dart_os</strong>, or scan the joining QR code:"
      infoImg: "/assets/img/dart-os-reddit-qr-code.png"
      link: "https://www.reddit.com/r/dart_os/"
  follow:
    - name: Twitter
      icon: "fa fa-twitter"
      link: http://twitter.com/dart_os
      username: "@dart_os"
    # - name: Facebook
    #   icon: "fa fa-facebook"
    #   link: http://facebook.com/sys41x4
    - name: LinkedIn
      icon: "fa fa-linkedin"
      link: http://linkedin.com/in/sys41x4
    - name: GitLab
      icon: "fa fa-gitlab"
      link: http://gitlab.com/dart-os
    - name: GitHub
      icon: "fa fa-github"
      link: http://github.com/dart-os
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    - name: RSS
      icon: "fa fa-rss"
      link: /feed.xml

defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - '*.json'

# Used for defeating caching
version: 1
